### ISSUE TITLE
coin price bug

### ISSUE THREAD

**Issue by dgsus** [deso-protocol/core#29] opened 2021-06-09 09:25 UTC
team,

the salomon bug has been fixed however i'm still seeing accounts that their price are not making sense. 

https://github.com/bitclout/core/blob/2cbd77da61109303f3f961c227a414ab063a74d6/lib/constants.go#L78

It seems the bug is not only happening on buy option but sell too.

Please check https://bitclout.com/u/Petrh -> it seems the bug occurred in the sell option , different from salomon bug.
https://bitcloutsignal.com/history/petrh

Also please look at https://bitclout.com/u/speakinglight -> this seems to be like the salomon bug
https://bitcloutsignal.com/history/speakinglight

please look at this before we get more users onboarded, since this can be a significant challenge going forward if the creator coins are not always working correctly.

this might be a UI problem and not blockchain, if we go to signalclout we can see their real price.

petrh - should be around 555 usd
speakinglight - should be around 268 usd

thanks in advance!

**Comment by tijno** [comment] 2021-06-09 10:16
Ive seen this too and also seen some accounts use it as a way to scam investments. I didnt note the account ID but one was a imitation account of a well known account, and had used the bug i think to elevate price.

**Comment by dgsus** [comment] 2021-06-12 09:32
@diamondhands0 @maebeam is this not important? am i seeing this wrong?

**Comment by vinnymeller** [comment] 2021-06-16 04:21
I'm having this issue too, I want to buy my own coin but the price shows up as being far, far too high. With only 0.0008 coins currently in circulation, 49 bitclout will only get me ~3 creator coins:

![image](https://user-images.githubusercontent.com/19894025/122157171-fee2e700-ce2f-11eb-9261-6207f595c409.png)

![image](https://user-images.githubusercontent.com/19894025/122157211-14f0a780-ce30-11eb-976f-6bf3f903367b.png)

I'd like to buy my coin but I don't want to throw away all my bitclout if I have to go back and sell and suddenly its using the correct bonding curve :x

**Comment by tijno** [comment] 2021-06-17 19:50
another case here @maebeam @lazynina @diamondhands0 

coinprice 16k
0.11 coins in circulation

https://bitclout.com/posts/7905dc372e16dace1ba5f1032c8e1162dd7084041f158f161f61123d8ca31dfa

**Comment by drshenn** [comment] 2021-06-17 21:03
> another case here @maebeam @lazynina @diamondhands0
> 
> coinprice 16k
> 0.11 coins in circulation
> 
> https://bitclout.com/posts/7905dc372e16dace1ba5f1032c8e1162dd7084041f158f161f61123d8ca31dfa

![2021-06-18 00_02_23-papatya on BitClout](https://user-images.githubusercontent.com/86081358/122471890-806d7d00-cfc8-11eb-9e6d-252ac8735700.png)

≈ $598.85
Total USD Locked

this money is lost

**Comment by vinnymeller** [comment] 2021-06-17 21:20
@drshenn that's strange

for _mine_, the value is still all there. the bonding curve is just mad broken

I will get the same bitclout out that I put into it if I sell it
![image](https://user-images.githubusercontent.com/19894025/122473766-e980d080-cf87-11eb-912f-f5b4c2d9664e.png)

though that doesn't seem to be the case in the issue you posted?

**Comment by drshenn** [comment] 2021-06-17 21:29
![2021-06-17 21_30_12-papatya on BitClout - Opera](https://user-images.githubusercontent.com/86081358/122474631-2a9ad400-cfcc-11eb-9d2a-cca7a8d097e4.png)
My money was lost. It is really interesting. I hope the problem is solved.

**Comment by maebeam** [comment] 2021-06-17 21:32
Thanks for investigating this everyone! The core devs are working on a solution. I'll update this issue once we have more information.

**Comment by drshenn** [comment] 2021-06-17 21:34
> Thanks for investigating this everyone! The core devs are working on a solution. I'll update this issue once we have more information.

thank you so much. so can i get my money back? 600 dollars is a lot of money for Turkey.

**Comment by maebeam** [comment] 2021-06-17 21:37
The core devs have never seen a case where these trades have resulted in a loss of funds. If you think you lost funds I would suggest emailing node.admin@bitclout.com

**Comment by drshenn** [comment] 2021-06-17 21:39
> The core devs have never seen a case where these trades have resulted in a loss of funds. If you think you lost funds I would suggest emailing [node.admin@bitclout.com](mailto:node.admin@bitclout.com)

My money is lost. All transactions are already on the blockchain. I will send an e-mail but will I get a response?

**Comment by drshenn** [comment] 2021-06-18 14:57
All the problem happened after these actions. This is a very dangerous bug. After this action, the money disappeared from the account. I tried to get the money with small attempts but it didn't work. Please save my money.
![unnamed](https://user-images.githubusercontent.com/86081358/122580306-7c8c3a00-d05e-11eb-8ed4-f2403da8c81d.png)

https://explorer.cloutangel.com/address/@papatya

**Comment by drshenn** [comment] 2021-06-18 15:02
> The core devs have never seen a case where these trades have resulted in a loss of funds. If you think you lost funds I would suggest emailing [node.admin@bitclout.com](mailto:node.admin@bitclout.com)

I sent an e-mail to this address. But this is also a very important bug. It's not just a circulation error. Money is lost as well.

https://docs.bitclout.com/devs/bug-bounty I also sent a message to the mail at this address. When will you get back to me? I can't use my 3 bitclout right now.

**Comment by drshenn** [comment] 2021-06-20 16:50
Nobody answers my mail. I lost my money for 3 days. 


<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg2NDA5ODMxOQ==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg2NDA5ODMxOQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg2NDA5ODMxOQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-864098319" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="87d49686b258d63864127992f3be0882a4a0ee59a1bbdf240c2fe19e6d1bbb33" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">@maebeam&nbsp;@lazynina&nbsp;@diamondhands0</task-lists></div><form class="js-comment-update" id="issuecomment-864098319-edit-form" action="https://github.com/bitclout/core/issue_comments/864098319" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg2NDEwMjE1OQ==" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg2NDEwMjE1OQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg2NDEwMjE1OQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><br class="Apple-interchange-newline">

</div></div>

**Comment by drshenn** [comment] 2021-06-22 18:36
We see the transactions better on this site. https://bitcloutsignal.com/history/papatya
![2021-06-22 21_35_05-@BitcloutSignal](https://user-images.githubusercontent.com/86081358/122980857-d617a000-d3a1-11eb-868d-6a809a23dd37.png)

**Comment by tijno** [comment] 2021-06-23 06:11
just noting another example here
https://bitclout.com/u/biteagle

4.5k coin price
with $4.6 locked

**Comment by tijno** [comment] 2021-06-26 14:11
Another one

https://bitclout.com/u/speakingLight

![20210626-bFilr639](https://user-images.githubusercontent.com/69529928/123515795-cee9de00-d690-11eb-92c8-7bfa7d1396ee.png)

**Comment by drshenn** [comment] 2021-06-26 18:03
I really can't understand. There is a very important bug. But nobody answers. Still no one has replied to my email.

**Comment by drshenn** [comment] 2021-06-26 18:45
![2021-06-26 21_44_04-Pegleg on BitClout](https://user-images.githubusercontent.com/86081358/123522714-bea12580-d6c7-11eb-824b-9b6137c7baac.png)
This account is also missing $300.

**Comment by diamondhands0** [comment] 2021-06-27 07:49
Hey everyone, just updating here. We're very familiar with this bug, and we refer to it as the Salomon bug, named after @salomon who first triggered it (@speakingLight was also an early user who triggered it). Importantly, because all rankings are done using BitClout locked rather than price, this issue is mainly cosmetic and does not affect any of the core functionality.

If you grep the codebase and commit history for salomon you should see a partial fix from a while ago that significantly decreases one's ability to throw off the price. In particular, it now requires deliberate effort to trigger it, and the price will only be ~10k max in the worst case vs the hundreds of millions we were seeing before.

Again, this does not affect any core functionality since BitClout locked is what's used for all calculations; it just results in a price that is at odds with how much is locked.

I'm leaving this open until it is 100% fixed, but wanted to let everyone know that we're aware of this issue and update with current status.

**Comment by drshenn** [comment] 2021-06-27 12:38
> Hey everyone, just updating here. We're very familiar with this bug, and we refer to it as the Salomon bug, named after @salomon who first triggered it (@speakingLight was also an early user who triggered it). Importantly, because all rankings are done using BitClout locked rather than price, this issue is mainly cosmetic and does not affect any of the core functionality.
> 
> If you grep the codebase and commit history for salomon you should see a partial fix from a while ago that significantly decreases one's ability to throw off the price. In particular, it now requires deliberate effort to trigger it, and the price will only be ~10k max in the worst case vs the hundreds of millions we were seeing before.
> 
> Again, this does not affect any core functionality since BitClout locked is what's used for all calculations; it just results in a price that is at odds with how much is locked.
> 
> I'm leaving this open until it is 100% fixed, but wanted to let everyone know that we're aware of this issue and update with current status.

So you are trying to solve the problem. Just hearing that made me happy. So I can use my money. (I bought creator coin with bitclout. After purchasing, these creator coins were deleted. In the solomon bug, the money was not lost. In my problem, the money is lost. )

I really trust the bitclout project. It is a game changer movement. I even aim to expand this project in my country.

I worked on a blockchain-based social media project for 3-4 years. I want to use my experience here. Due to Covid, medical work is very busy right now. After things get comfortable, I'll create a dev team. I don't want to say much about the project here, but we will revolutionize the Play Store and App Store. (You know, Turkey is a very important country for the mobile application industry. If an application wants to be successful in the Middle East and Balkan markets, the Turkish market has to be involved.) Since we will use the Bitclout infrastructure completely in our projects, we have to rely on the project's blockchain infrastructure. That's why we are afraid of the slightest bug.

**Comment by CoderDrShen** [comment] 2021-07-02 13:26
https://bitclout.com/posts/e250f57130c494fb112b04d1c47d86c9a6b7df3c039e0921858413879eb4a120?feedTab=Global

@maebeam @lazynina @diamondhands0

How many software developers do you have in your development team? 50? 101? You are very fast. Thank you very much. I knew very well that my money would not go to waste. I know the Bitclout project will revolutionize. We will join this revolution soon. There have already been 8 revolutionaries in my dev team. We will start the projects as soon as possible. We will destroy Twitter and Facebook in Google Play and App Store.

**Comment by binoyxj** [comment] 2021-07-16 12:10
Any update on this? I'm personally suffering from this bug since day 1. Heard from @maebeam that this will be addressed along with the NFT feature drop, but since it's such an integral feature and no ETA on the NFT feature launch have me worried.

**Comment by mvanhalen** [comment] 2021-07-31 12:16
I have one here https://bitclout.com/u/CreatorCapital?tab=creator-coin account is 15 days old according to https://www.prosperclout.com/u/CreatorCapital?tab=overview

**Comment by tijno** [comment] 2021-07-31 12:24
This is as a result of NFTs with 100% Coin Royalty - there's been a few examples last 12 hours or so:

https://bitclout.com/u/100CoinHolderRoyaltyNFTs
![20210731-afq59hAg](https://user-images.githubusercontent.com/69529928/127739765-44ad6128-ac6e-48f7-8f1a-3dd59554f889.png)

https://bitclout.com/u/infinityprice
![20210731-ydFSQ7dL](https://user-images.githubusercontent.com/69529928/127739768-47cc844e-2c16-493f-b4ba-52c7b141bf6d.png)

https://bitclout.com/u/TestingNFTRoyalty
![20210731-JGNNhhVP](https://user-images.githubusercontent.com/69529928/127739770-2629b749-a192-4d31-9496-1253e6b3533f.png)

**Comment by speakingLight** [comment] 2021-08-03 02:45
thank you for the reply, sorry for my public discomfort from experiencing
this glitch
i appreciate the functionality of the platform and will begin posting again
soon
i'm just some weird sensitive guy that likes to say things

**Comment by sungkhum** [comment] 2021-11-04 17:12
Just pinging this - seeing it come up a fair amount on my creator coin listing sites and waiting for a complete fix.

**Comment by maebeam** [comment] 2021-12-21 23:52
Hey everyone,

With the addition of NFTs the "coin price" of a profile is not a recommended metric to use. The "total deso locked" in a profile is always reliable and can be used to rank creators.

Since there is no fix for this behavior and the core devs don't have any near term plans to change this behavior I'm going to close this issue. Please let me know if you have any questions / comments / concerns.

**Closed by maebeam** 2021-12-21 23:52 UTC
