### ISSUE TITLE
Postgres error halts / corrupts syncing from block 98475 related  to DAO TransferRestrictionStatus 

### ISSUE THREAD

**Issue by mvanhalen** [deso-protocol/core#198] opened 2022-01-26 09:15 UTC
During Postgres sync with the last Postgres Dao updates got this error:

` server.go:1147] Server._handleBlock: Received block ( 98475 / 98627 ) from Peer [ Remote Address: 34.123.41.111:17000 PeerID=32 ]
E0126 08:54:21.794215       1 server.go:1141] Server._handleBlock: Encountered an error processing block <Header: < 98475, 00000000000058e8268e3ca270ab453fdd41382623c5ca30516d6ddf95b7b764, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 34.123.41.111:17000 PeerID=32 ]: Error while processing block: : ProcessBlock: Problem upserting block and transactions: ERROR #23502 null value in column "transfer_restriction_status" violates not-null constraint`

Seem related to Dao coin insert/update at first glance. Related to 
`DAOCoinTransferRestrictionStatus TransferRestrictionStatus pg:"dao_coin_transfer_restriction_status"`

When this block hits in the sync all blocks after get status 26 in pg_blocks.

Looking for a solution or fix.

So transfer_restriction_status SMALLINT NOT NULL seems to get a NULL value and rejects that.
`type PGMetadataDAOCoin struct {
	tableName struct{} `pg:"pg_metadata_dao_coins"`

	TransactionHash           *BlockHash           `pg:",pk,type:bytea"`
	ProfilePublicKey          []byte               `pg:",type:bytea"`
	OperationType             DAOCoinOperationType `pg:",use_zero"`
	CoinsToMintNanos          string
	CoinsToBurnNanos          string
	TransferRestrictionStatus `pg:",use_zero"`
}`

Might be related to `pg:",use_zero"` for that enum type. 

Would transfer_restriction_status SMALLINT NOT NULL with DEFAULT 0 added solve the issue? Took me 2 days to sync to get to that point. Any ideas are welcome.

This PR from @tijno brings us to block 98477  #201  But still seems something goes wrong with the status field

**Comment by diamondhands0** [comment] 2022-01-26 22:09
Hey @mvanhalen, can you please make sure you're running release 2.02, which contains this commit?
* c56e1cbfb4c1458045874817bdd7f0193aaa4cab

If this doesn't solve your issue let us know.

**Comment by mvanhalen** [comment] 2022-01-26 22:50
> Hey @mvanhalen, can you please make sure you're running release 2.02, which contains this commit?
> 
> * [c56e1cb](https://github.com/deso-protocol/core/commit/c56e1cbfb4c1458045874817bdd7f0193aaa4cab)
> 
> If this doesn't solve your issue let us know.

Yeah had all these changes uncluded. That includes a typo fix also I reported. So pretty sure this version will get stuck at the same point. It´s trying to insert a null value on a non nullable column. Not sure why but it´s related to TransferRestrictionStatus of DAO coins.

Thanks for the follow up though.

**Comment by diamondhands0** [comment] 2022-01-27 00:34
Hmm... this is super weird. I've looked through the code several times now and can't see how it could possibly break like this. Is it possible the migrations didn't run on your Postgres db?

**Comment by tijno** [comment] 2022-01-27 09:26
Im doing full clean postgres sync with 2.0.3 right now - it will take a while before I get to 98k blocks but will report results.

**Comment by tijno** [comment] 2022-01-28 09:23
@diamondhands0 same issue completely clean postgres sync:

```
0128 07:33:22.195514       1 server.go:1141] Server._handleBlock: Encountered an error processing block <Header: < 98475, 00000000000058e8268e3ca270ab453fdd41382623c5ca30516d6ddf95b7b764, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=3 ]: Error while processing block: : ProcessBlock: Problem upserting block and transactions: ERROR #23502 null value in column "transfer_restriction_status" of relation "pg_metadata_dao_coins" violates not-null constraint
```

**Comment by tijno** [comment] 2022-01-28 10:21
Is there a way to rollback pg db to 98474 ? Or is a full resync required ?

**Comment by mvanhalen** [comment] 2022-01-28 10:32
> 

Thanks @tijno  I will try dao_coin_transfer_restriction_status smallint DEFAULT 0, see if that fixes it. 0 is unrestricted the default value in diamond also. My sync is not at that point yet. Will be later today/tomorrow. I think some conversion issue with the TransActionRestriction Status type is the issue.

**Comment by tijno** [comment] 2022-01-29 11:44
@mvanhalen clean sync with `transfer_restriction_status` set to allow null (manually after tables created)

> E0129 11:16:06.914856       1 server.go:1141] Server._handleBlock: Encountered an error processing block <Header: < 98477, 0000000000006a47315898c0b8cabbcdb9ad885638ce82361144eaca1b960475, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=13 ]: Error while processing block: : ConnectBlock: : ConnectTransaction: : _helpConnectCoinTransfer: Coin nanos being transferred 500000000000 exceeds user's coin balance [0 0 0 0]: RuleErrorCoinTransferInsufficientCoins

**Comment by mvanhalen** [comment] 2022-01-29 13:50
Clean  sync with default 1 for the transfer_restriction_status field set in Postgres failed at the same 98475 block again.

**Comment by tijno** [comment] 2022-01-29 14:40
Hopefully this will help diagnose this additional issue.

## Issues

* A Transfer DAO Coins after a DAO Coin Burn causes possible issue with balance
* Change of `transfer_restriction_status` does not set `pg_metadata_dao_coins.transfer_restriction_status` field

## Summarising the timeline on firstdao 

**1) minted 10,000 x  1e9 DAOCoin**

Block | Index | TxType | TxID
98475 | 141 | DAO_COIN | 3JuEU5Mv8ctYEz5AU8aBUYQutyANy2mZDrp7Aqjg91zb9iL5SKYkX2

**2) update_transfer_restriction_status to `permanently unrestricted`**

98475 | 173 | DAO_COIN | 3JuETrYzbth3TukCjUUEk3Wt9852rgtfUvdC6ZVx9x5mBDaqYZoTS6

**3) burned 9,000 x 1e9 DAOCoin, so 1,000 x 1e9 Left**

98475 | 314 | DAO_COIN | 3JuETSLpbf4dyJhkCy7ZYV6QUvm1TT3MH4pPrYRR2M5hco4d8ryBLS

**4) transfer 500 x 1e9 to `@100`**

This Tx fails in Postgress with the `_helpConnectCoinTransfer: Coin nanos being transferred 500000000000 exceeds user's coin balance [0 0 0 0]: RuleErrorCoinTransferInsufficientCoins` error.

98477 | 44 | DAO_COIN_TRANSFER | 3JuETm4MfJif66tfmXGkT1DkJdYrg2gymefnHWDak2T2cXgSmQhWUJ

## State in postgres at TIP 98476

**pg_profiles**

* firstdao: 1 daocoin holder, circulation: 1000 x 1e9, dao restriction: 3

**pg_dao_coin_balances**

* firstdao: balance: 1000 x 1e9, has purchased: 0
* 100: balance: 0

**pg_metadata_dao_coins**

* firstdao: showing entries for mint, change transfer restriction and burn

NOTE: `transfer_restriction_status` is metadata is `NULL` for `operation_type=3` - it was set to `permanently unrestricted` so it should be `3`. Looks like another bug?

**pg_metadata_dao_coin_transfers**

Not showing any entries for firstdao.


## Current account status on normal chain, not postgres:

<img width="467" alt="CleanShot 2022-01-29 at 14 17 37@2x" src="https://user-images.githubusercontent.com/69529928/151664403-6a07e222-1df0-4e33-a1d0-f3f7eb327fdc.png">

**Comment by StarGeezerPhil** [comment] 2022-01-29 15:54
@tijno @mvanhalen thank you for keeping on at this.

Just to add - subscribed. Still having issues performing a single sync beyond block 2 since rebuild, but will try everything clear again with the latest images. 

I'm new to docker - am I using the right image source: docker.io/desoprotocol/backend:latest

**Comment by tijno** [comment] 2022-01-29 16:06
@StarGeezerPhil lets chat on discord about that - ill try and help

**Comment by StarGeezerPhil** [comment] 2022-02-02 12:07
@diamondhands0 @maebeam 
Could we have feedback/resolution on this issue?

I'm stuck on 98476/7 - exactly the same as @tijno as reported in detail above.

I rebuilt node using the updated backend, clean postgres instance.
Paused sync after the initial db setup and manually modified the erroneous column (pg_metadata_dao_coins.transfer_restriction_status, allowing null values).
Then restarted sync and allowed to progress.

It progressed beyond the initial hold-up, but stuck same as @mvanhalen / @tijno.

**Comment by diamondhands0** [comment] 2022-02-03 14:57
Hey all, we’ve been investigating this but we’re making it our top priority to fix it today. Hoping we can have it fixed for you all shortly!

**Comment by tijno** [comment] 2022-02-03 16:48
thx @diamondhands0 - ones you have a fix can you trigger backend image update - as that doesnt happen automatically to core changes i believe.

**Comment by diamondhands0** [comment] 2022-02-04 09:07
Hey all, @lazynina fixed the issue. You can see the fix here. It turned out to be a pretty simple fix. Sorry for all the hassle:
* https://github.com/deso-protocol/core/pull/208#pullrequestreview-872695605

**To use the fix, you should just be able to restart your node with core version 2.0.4. I don't think a resync is required.**

**Comment by StarGeezerPhil** [comment] 2022-02-04 09:27
@diamondhands0 @lazynina thank you for the fix.

I updated and restarted, but after what looked like a successful start and receiving blocks beyond 98476 backend exited with code 2 and a string of errors - I think prior issue caused missing transactions, so they're missing for references.

Therefore, believe this is a full resync for anyone affected.

Example errors included below if this helps you diagnose further.

> I0204 09:22:08.978579       1 server.go:510] Received header bundle with 0 headers in state SYNCING_BLOCKS from peer [ Remote Address: 35.232.92.5:17000 PeerID=36 ]. Downloaded ( 101246 / 101246 ) total headers
I0204 09:22:09.559726       1 server.go:1147] Server._handleBlock: Received block ( 98494 / 101246 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=36 ]
E0204 09:22:09.655481       1 blockchain.go:1214] MarkBlockInvalid: Block height: 98494, Block hash: 0000000000004bae582cc55a8bd1602ff3b50f148773dcad95c1ac46fa2ebc40, Error: ConnectBlock: : ConnectTransaction: : RuleErrorCannotTransferNonExistentNFT
E0204 09:22:09.655522       1 blockchain.go:1215] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0204 09:22:09.655548       1 blockchain.go:1216] goroutine 181 [running]:
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0xc00d636540, 0xc0b018dc00, {0xc00d607630, 0x4b})
/deso/src/core/lib/blockchain.go:1216 +0x14a
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000f44580, 0xc00d3f9890, 0x8a)
/deso/src/core/lib/blockchain.go:1917 +0x1fa5
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc0010dc180, 0xc00affc240, 0xc00d3f9890)
/deso/src/core/lib/server.go:1193 +0x3e5
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xf4241, 0x0)
/deso/src/core/lib/server.go:1494 +0x18d
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc0010dc180)
/deso/src/core/lib/server.go:1534 +0x19c
created by github.com/deso-protocol/core/lib.(*Server).Start
/deso/src/core/lib/server.go:1710 +0xb1
E0204 09:22:09.655552       1 blockchain.go:1223] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
E0204 09:22:09.655563       1 server.go:1141] Server._handleBlock: Encountered an error processing block <Header: < 98494, 0000000000004bae582cc55a8bd1602ff3b50f148773dcad95c1ac46fa2ebc40, 1 >, Signer Key: BC1YLh768bVj2R3QpSiduxcvn7ipxF3L3XHsabZYtCGtsinUnNrZvNN>. Disconnecting from peer [ Remote Address: 35.232.92.5:17000 PeerID=36 ]: Error while processing block: : ConnectBlock: : ConnectTransaction: : RuleErrorCannotTransferNonExistentNFT
E0204 09:22:09.655728       1 peer.go:1060] ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp 172.18.0.2:40750->35.232.92.5:17000: use of closed network connection
E0204 09:22:09.655769       1 peer.go:919] Peer.inHandler: Can't read message from peer [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=36 ]: ReadDeSoMessage: : ReadMessage: Could not read payload for message type (BLOCK): read tcp 172.18.0.2:40750->35.232.92.5:17000: use of closed network connection
I0204 09:22:09.679944       1 peer.go:399] StartDeSoMessageProcessor: Cleaning up message queue for peer: [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=36 ]
I0204 09:22:09.680030       1 peer.go:415] StartDeSoMessageProcessor: Stopping because peer disconnected: [ Remote Address: 35.232.92.5:17000, DISCONNECTED PeerID=36 ]
I0204 09:22:15.004990       1 base.go:279] Refreshing USD to ETH exchange rate
I0204 09:22:15.538000       1 base.go:268] Refreshing USD to BTC exchange rate
I0204 09:22:15.538066       1 base.go:286] New USD to ETH exchange rate: 2832.790000
I0204 09:22:16.036828       1 base.go:275] New USD to BTC exchange rate: 37998.160000
I0204 09:22:16.267059       1 base.go:228] Refreshing exchange rate...
I0204 09:22:16.853446       1 base.go:167] Blockchain exchange rate: 4685 [4685 4685 4685 4685 4685 4685 4685 4685 4685 4685]
I0204 09:22:16.853499       1 base.go:232] Blockchain.com price (USD cents): 4685
I0204 09:22:17.030898       1 base.go:239] Coinbase price (USD Cents): 4718
I0204 09:22:17.030931       1 base.go:264] Final exchange rate: 4730
I0204 09:22:23.674578       1 peer.go:1011] Peer.Start: Starting peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
I0204 09:22:23.674657       1 peer.go:411] StartDeSoMessageProcessor: Starting for peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
I0204 09:22:23.886025       1 server.go:510] Received header bundle with 0 headers in state SYNCING_BLOCKS from peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]. Downloaded ( 101246 / 101246 ) total headers
I0204 09:22:24.461338       1 server.go:1147] Server._handleBlock: Received block ( 98494 / 101246 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
E0204 09:22:24.551873       1 blockchain.go:1214] MarkBlockInvalid: Block height: 98494, Block hash: 0000000000004bae582cc55a8bd1602ff3b50f148773dcad95c1ac46fa2ebc40, Error: ConnectBlock: : ConnectTransaction: : RuleErrorCannotTransferNonExistentNFT
E0204 09:22:24.551913       1 blockchain.go:1215] MarkBlockInvalid: Printing stack trace so error is easy to find: 
E0204 09:22:24.551933       1 blockchain.go:1216] goroutine 181 [running]:
runtime/debug.Stack()
/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/deso-protocol/core/lib.(*Blockchain).MarkBlockInvalid(0xc00e1bd968, 0xc0b018dc00, {0xc00e198d20, 0x4b})
/deso/src/core/lib/blockchain.go:1216 +0x14a
github.com/deso-protocol/core/lib.(*Blockchain).ProcessBlock(0xc000f44580, 0xc00dcf4240, 0x8a)
/deso/src/core/lib/blockchain.go:1917 +0x1fa5
github.com/deso-protocol/core/lib.(*Server)._handleBlock(0xc0010dc180, 0xc00a8cd8c0, 0xc00dcf4240)
/deso/src/core/lib/server.go:1193 +0x3e5
github.com/deso-protocol/core/lib.(*Server)._handlePeerMessages(0xf4241, 0x0)
/deso/src/core/lib/server.go:1494 +0x18d
github.com/deso-protocol/core/lib.(*Server).messageHandler(0xc0010dc180)
/deso/src/core/lib/server.go:1534 +0x19c
created by github.com/deso-protocol/core/lib.(*Server).Start
/deso/src/core/lib/server.go:1710 +0xb1

**Comment by tijno** [comment] 2022-02-05 14:46
@lazynina confirmed new issue - same as @StarGeezerPhil mentioned above - see #211

**Closed** 2022-02-05 14:48 UTC
